// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace Splice.Testing.Tokens.TestTokenV1;

internal static class PackageRegistration_da294b5651ed00af8565fd31351d0c1d8778f10393d250e32c9844311f681436
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register()
    {
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Splice.Testing.Tokens.TestTokenV1.Token>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Testing.Tokens.TestTokenV1.Token>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Splice.Testing.Tokens.TestTokenV1.TokenAllocation>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Testing.Tokens.TestTokenV1.TokenAllocation>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Splice.Testing.Tokens.TestTokenV1.TokenRules>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Testing.Tokens.TestTokenV1.TokenRules>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Splice.Testing.Tokens.TestTokenV1.TokenTransferOffer>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Testing.Tokens.TestTokenV1.TokenTransferOffer>();
    }
}
