// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Testing.Tokens.TestTokenV1;

/// <summary>
/// Generated from Daml template Splice.Testing.Tokens.TestTokenV1:TokenTransferOffer
/// </summary>
public sealed partial record TokenTransferOffer(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("transfer")] global::Splice.Api.Token.TransferInstructionV1.Transfer Transfer
) : global::Daml.Runtime.Contracts.ITemplate, global::Daml.Runtime.Contracts.IImplements<global::Splice.Api.Token.TransferInstructionV1.ITransferInstruction>, global::Daml.Runtime.Contracts.IImplements<global::Splice.Api.Token.HoldingV1.IHolding>, global::Daml.Runtime.Contracts.IHasChoices<TokenTransferOffer>, global::Daml.Runtime.Data.IDamlRecord<TokenTransferOffer>
{
    /// <summary>Gets the template identifier.</summary>
    public static global::Daml.Runtime.Data.Identifier TemplateId { get; } = new("da294b5651ed00af8565fd31351d0c1d8778f10393d250e32c9844311f681436", "Splice.Testing.Tokens.TestTokenV1", "TokenTransferOffer");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "da294b5651ed00af8565fd31351d0c1d8778f10393d250e32c9844311f681436";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-test-token-v1";

    /// <summary>Gets the package version.</summary>
    public static global::System.Version PackageVersion { get; } = new(1, 0, 1);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static global::Daml.Runtime.Contracts.DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, global::Daml.Runtime.Contracts.DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("transfer", Transfer.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TokenTransferOffer FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new TokenTransferOffer(
        Transfer: global::Splice.Api.Token.TransferInstructionV1.Transfer.FromRecord(record.GetRequiredField("transfer").As<global::Daml.Runtime.Data.DamlRecord>())
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("transfer", global::Splice.Api.Token.TransferInstructionV1.Transfer.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "transfer"), context.Field("transfer")))
        );
    }

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<TokenTransferOffer, global::Daml.Runtime.Data.DamlUnit, global::Daml.Runtime.Data.DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => global::Daml.Runtime.Data.DamlRecord.Create(),
        ArgumentDecoder = val => val is global::Daml.Runtime.Data.DamlRecord { Fields.Count: 0 } ? global::Daml.Runtime.Data.DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => global::Daml.Runtime.Data.DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return global::Daml.Runtime.Data.DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    public static global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Commands.IChoice> Choices { get; } = [ChoiceArchive];

}


/// <summary>
/// Typed-submitter extensions for <see cref="TokenTransferOffer"/>. The
/// <see cref="TryCreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class TokenTransferOfferSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="TokenTransferOffer"/> contract on the ledger.
    /// The submitter is passed explicitly via <paramref name="submitter"/>. The static
    /// analyzer could not resolve the Daml <c>signatory</c> clause to payload-field
    /// references — typically because the expression involves the template key, a
    /// constant, or a function call. <see cref="SubmitterInfo"/> implicitly converts
    /// from a single <c>Party</c>, so single-party callers still pass one literal.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>).</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Contracts.ContractId<TokenTransferOffer>>> TryCreateAsync(
        this global::Daml.Ledger.Abstractions.ILedgerWriter client,
        TokenTransferOffer payload,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);
        global::System.ArgumentNullException.ThrowIfNull(payload);

        return global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TryCreateAsync<TokenTransferOffer>(client, payload, submitter, configure: configure, cancellationToken: cancellationToken);
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="global::Splice.Testing.Tokens.TestTokenV1.TokenTransferOffer"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>SingleCommandExtensions.TrySubmitSingleAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class TokenTransferOfferNonContractExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Archive choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand ArchiveCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Testing.Tokens.TestTokenV1.TokenTransferOffer> contractId)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Testing.Tokens.TestTokenV1.TokenTransferOffer.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("Archive"),
            global::Daml.Runtime.Data.DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the Archive choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Daml.Runtime.Data.DamlUnit</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit>> TryArchiveAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Testing.Tokens.TestTokenV1.TokenTransferOffer> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit> ProjectArchiveResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Testing.Tokens.TestTokenV1.TokenTransferOffer.ChoiceArchive, contractId);
}
