// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using Daml.Runtime.Stdlib;

namespace Splice.Ans;

public sealed partial record AnsEntry
{
    /// <summary>
    /// Choice argument type for AnsEntry_Renew.
    /// </summary>
    public sealed record AnsEntry_Renew(
        [property: global::Daml.Runtime.Data.DamlFieldAttribute("extension")] global::Daml.Runtime.Stdlib.RelTime Extension
    ) : global::Daml.Runtime.Data.IDamlRecord<AnsEntry_Renew>
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("extension", Extension.ToRecord())
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static AnsEntry_Renew FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AnsEntry_Renew(
            Extension: global::Daml.Runtime.Stdlib.RelTime.FromRecord(record.GetRequiredField("extension").As<global::Daml.Runtime.Data.DamlRecord>())
        );

        /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return global::Daml.Runtime.Data.DamlRecord.Create(
                global::Daml.Runtime.Data.DamlField.Create("extension", global::Daml.Runtime.Stdlib.RelTime.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "extension"), context.Field("extension")))
            );
        }

    }
}
