// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml record AnsEntryContext_CollectInitialEntryPaymentResult
/// </summary>
public sealed record AnsEntryContext_CollectInitialEntryPaymentResult(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("entryCid")] global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntry> EntryCid,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("subscriptionStateCid")] global::Daml.Runtime.Contracts.ContractId<global::Splice.Wallet.Subscriptions.SubscriptionIdleState> SubscriptionStateCid
) : global::Daml.Runtime.Data.IDamlRecord<AnsEntryContext_CollectInitialEntryPaymentResult>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("entryCid", EntryCid.ToDamlValue()),
        global::Daml.Runtime.Data.DamlField.Create("subscriptionStateCid", SubscriptionStateCid.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsEntryContext_CollectInitialEntryPaymentResult FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AnsEntryContext_CollectInitialEntryPaymentResult(
        EntryCid: new global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntry>(record.GetRequiredField("entryCid").As<global::Daml.Runtime.Contracts.DamlContractId>().Value),
        SubscriptionStateCid: new global::Daml.Runtime.Contracts.ContractId<global::Splice.Wallet.Subscriptions.SubscriptionIdleState>(record.GetRequiredField("subscriptionStateCid").As<global::Daml.Runtime.Contracts.DamlContractId>().Value)
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("entryCid", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "entryCid"), context.Field("entryCid"))),
            global::Daml.Runtime.Data.DamlField.Create("subscriptionStateCid", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "subscriptionStateCid"), context.Field("subscriptionStateCid")))
        );
    }

}
