// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml template Splice.Ans:AnsEntryContext
/// </summary>
public sealed partial record AnsEntryContext(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("dso")] global::Daml.Runtime.Data.Party Dso,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("user")] global::Daml.Runtime.Data.Party User,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("name")] string Name,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("url")] string Url,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("description")] string Description,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("reference")] global::Daml.Runtime.Contracts.ContractId<global::Splice.Wallet.Subscriptions.SubscriptionRequest> Reference
) : global::Daml.Runtime.Contracts.ITemplate, global::Daml.Runtime.Contracts.IHasChoices<AnsEntryContext>, global::Daml.Runtime.Data.IDamlRecord<AnsEntryContext>
{
    /// <summary>Gets the template identifier.</summary>
    public static global::Daml.Runtime.Data.Identifier TemplateId { get; } = new("cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1", "Splice.Ans", "AnsEntryContext");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-amulet-name-service";

    /// <summary>Gets the package version.</summary>
    public static global::System.Version PackageVersion { get; } = new(0, 1, 24);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static global::Daml.Runtime.Contracts.DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, global::Daml.Runtime.Contracts.DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("dso", Dso.ToDamlValue()),
        global::Daml.Runtime.Data.DamlField.Create("user", User.ToDamlValue()),
        global::Daml.Runtime.Data.DamlField.Create("name", new global::Daml.Runtime.Data.DamlText(Name)),
        global::Daml.Runtime.Data.DamlField.Create("url", new global::Daml.Runtime.Data.DamlText(Url)),
        global::Daml.Runtime.Data.DamlField.Create("description", new global::Daml.Runtime.Data.DamlText(Description)),
        global::Daml.Runtime.Data.DamlField.Create("reference", Reference.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsEntryContext FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AnsEntryContext(
        Dso: global::Daml.Runtime.Data.Party.FromDamlValue(record.GetRequiredField("dso").As<global::Daml.Runtime.Data.DamlParty>()),
        User: global::Daml.Runtime.Data.Party.FromDamlValue(record.GetRequiredField("user").As<global::Daml.Runtime.Data.DamlParty>()),
        Name: record.GetRequiredField("name").As<global::Daml.Runtime.Data.DamlText>().Value,
        Url: record.GetRequiredField("url").As<global::Daml.Runtime.Data.DamlText>().Value,
        Description: record.GetRequiredField("description").As<global::Daml.Runtime.Data.DamlText>().Value,
        Reference: new global::Daml.Runtime.Contracts.ContractId<global::Splice.Wallet.Subscriptions.SubscriptionRequest>(record.GetRequiredField("reference").As<global::Daml.Runtime.Contracts.DamlContractId>().Value)
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("dso", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "dso"), context.Field("dso"))),
            global::Daml.Runtime.Data.DamlField.Create("user", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "user"), context.Field("user"))),
            global::Daml.Runtime.Data.DamlField.Create("name", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "name"), context.Field("name"))),
            global::Daml.Runtime.Data.DamlField.Create("url", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "url"), context.Field("url"))),
            global::Daml.Runtime.Data.DamlField.Create("description", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "description"), context.Field("description"))),
            global::Daml.Runtime.Data.DamlField.Create("reference", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "reference"), context.Field("reference")))
        );
    }

    /// <summary>
    /// Exercise the AnsEntryContext_CollectEntryRenewalPayment choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsEntryContext, AnsEntryContext_CollectEntryRenewalPayment, global::Splice.Ans.AnsEntryContext_CollectEntryRenewalPaymentResult> ChoiceAnsEntryContext_CollectEntryRenewalPayment { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AnsEntryContext_CollectEntryRenewalPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsEntryContext_CollectEntryRenewalPayment.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AnsEntryContext_CollectEntryRenewalPaymentResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AnsEntryContext.AnsEntryContext_CollectEntryRenewalPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AnsEntryContext_CollectEntryRenewalPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsEntryContext_CollectInitialEntryPayment choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsEntryContext, AnsEntryContext_CollectInitialEntryPayment, global::Splice.Ans.AnsEntryContext_CollectInitialEntryPaymentResult> ChoiceAnsEntryContext_CollectInitialEntryPayment { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AnsEntryContext_CollectInitialEntryPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsEntryContext_CollectInitialEntryPayment.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AnsEntryContext_CollectInitialEntryPaymentResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AnsEntryContext.AnsEntryContext_CollectInitialEntryPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AnsEntryContext_CollectInitialEntryPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsEntryContext_RejectEntryInitialPayment choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsEntryContext, AnsEntryContext_RejectEntryInitialPayment, global::Splice.Ans.AnsEntryContext_RejectEntryInitialPaymentResult> ChoiceAnsEntryContext_RejectEntryInitialPayment { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AnsEntryContext_RejectEntryInitialPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsEntryContext_RejectEntryInitialPayment.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AnsEntryContext_RejectEntryInitialPaymentResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AnsEntryContext.AnsEntryContext_RejectEntryInitialPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AnsEntryContext_RejectEntryInitialPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsEntryContext_Terminate choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsEntryContext, AnsEntryContext_Terminate, global::Splice.Ans.AnsEntryContext_TerminateResult> ChoiceAnsEntryContext_Terminate { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AnsEntryContext_Terminate"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsEntryContext_Terminate.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AnsEntryContext_TerminateResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AnsEntryContext.AnsEntryContext_Terminate.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AnsEntryContext_TerminateResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsEntryContext, global::Daml.Runtime.Data.DamlUnit, global::Daml.Runtime.Data.DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => global::Daml.Runtime.Data.DamlRecord.Create(),
        ArgumentDecoder = val => val is global::Daml.Runtime.Data.DamlRecord { Fields.Count: 0 } ? global::Daml.Runtime.Data.DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => global::Daml.Runtime.Data.DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return global::Daml.Runtime.Data.DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    public static global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Commands.IChoice> Choices { get; } = [ChoiceAnsEntryContext_CollectEntryRenewalPayment, ChoiceAnsEntryContext_CollectInitialEntryPayment, ChoiceAnsEntryContext_RejectEntryInitialPayment, ChoiceAnsEntryContext_Terminate, ChoiceArchive];

}


/// <summary>
/// Typed-submitter extensions for <see cref="AnsEntryContext"/>. The
/// <see cref="TryCreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class AnsEntryContextSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="AnsEntryContext"/> contract on the ledger.
    /// The submitter is passed explicitly via <paramref name="submitter"/>. The static
    /// analyzer could not resolve the Daml <c>signatory</c> clause to payload-field
    /// references — typically because the expression involves the template key, a
    /// constant, or a function call. <see cref="SubmitterInfo"/> implicitly converts
    /// from a single <c>Party</c>, so single-party callers still pass one literal.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>).</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Contracts.ContractId<AnsEntryContext>>> TryCreateAsync(
        this global::Daml.Ledger.Abstractions.ILedgerWriter client,
        AnsEntryContext payload,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);
        global::System.ArgumentNullException.ThrowIfNull(payload);

        return global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TryCreateAsync<AnsEntryContext>(client, payload, submitter, configure: configure, cancellationToken: cancellationToken);
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="global::Splice.Ans.AnsEntryContext"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>SingleCommandExtensions.TrySubmitSingleAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class AnsEntryContextNonContractExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsEntryContext_CollectEntryRenewalPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AnsEntryContext_CollectEntryRenewalPaymentCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Splice.Ans.AnsEntryContext.AnsEntryContext_CollectEntryRenewalPayment argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsEntryContext.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AnsEntryContext_CollectEntryRenewalPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsEntryContext_CollectEntryRenewalPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AnsEntryContext_CollectEntryRenewalPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsEntryContext_CollectEntryRenewalPaymentResult>> TryAnsEntryContext_CollectEntryRenewalPaymentAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AnsEntryContext.AnsEntryContext_CollectEntryRenewalPayment argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsEntryContext_CollectEntryRenewalPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsEntryContext_CollectEntryRenewalPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsEntryContext_CollectInitialEntryPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AnsEntryContext_CollectInitialEntryPaymentCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Splice.Ans.AnsEntryContext.AnsEntryContext_CollectInitialEntryPayment argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsEntryContext.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AnsEntryContext_CollectInitialEntryPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsEntryContext_CollectInitialEntryPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AnsEntryContext_CollectInitialEntryPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsEntryContext_CollectInitialEntryPaymentResult>> TryAnsEntryContext_CollectInitialEntryPaymentAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AnsEntryContext.AnsEntryContext_CollectInitialEntryPayment argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsEntryContext_CollectInitialEntryPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsEntryContext_CollectInitialEntryPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsEntryContext_RejectEntryInitialPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AnsEntryContext_RejectEntryInitialPaymentCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Splice.Ans.AnsEntryContext.AnsEntryContext_RejectEntryInitialPayment argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsEntryContext.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AnsEntryContext_RejectEntryInitialPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsEntryContext_RejectEntryInitialPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AnsEntryContext_RejectEntryInitialPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsEntryContext_RejectEntryInitialPaymentResult>> TryAnsEntryContext_RejectEntryInitialPaymentAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AnsEntryContext.AnsEntryContext_RejectEntryInitialPayment argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsEntryContext_RejectEntryInitialPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsEntryContext_RejectEntryInitialPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsEntryContext_Terminate choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AnsEntryContext_TerminateCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Splice.Ans.AnsEntryContext.AnsEntryContext_Terminate argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsEntryContext.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AnsEntryContext_Terminate"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsEntryContext_Terminate choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AnsEntryContext_TerminateResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsEntryContext_TerminateResult>> TryAnsEntryContext_TerminateAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AnsEntryContext.AnsEntryContext_Terminate argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsEntryContext_TerminateCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsEntryContext_TerminateResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Archive choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand ArchiveCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsEntryContext.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("Archive"),
            global::Daml.Runtime.Data.DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the Archive choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Daml.Runtime.Data.DamlUnit</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit>> TryArchiveAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsEntryContext> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsEntryContext_CollectEntryRenewalPaymentResult> ProjectAnsEntryContext_CollectEntryRenewalPaymentResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsEntryContext.ChoiceAnsEntryContext_CollectEntryRenewalPayment, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsEntryContext_CollectInitialEntryPaymentResult> ProjectAnsEntryContext_CollectInitialEntryPaymentResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsEntryContext.ChoiceAnsEntryContext_CollectInitialEntryPayment, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsEntryContext_RejectEntryInitialPaymentResult> ProjectAnsEntryContext_RejectEntryInitialPaymentResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsEntryContext.ChoiceAnsEntryContext_RejectEntryInitialPayment, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsEntryContext_TerminateResult> ProjectAnsEntryContext_TerminateResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsEntryContext.ChoiceAnsEntryContext_Terminate, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit> ProjectArchiveResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsEntryContext.ChoiceArchive, contractId);
}
