// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using Daml.Runtime.Stdlib;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml record AnsRulesConfig
/// </summary>
public sealed record AnsRulesConfig(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("renewalDuration")] global::Daml.Runtime.Stdlib.RelTime RenewalDuration,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("entryLifetime")] global::Daml.Runtime.Stdlib.RelTime EntryLifetime,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("entryFee")] decimal EntryFee,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("descriptionPrefix")] string DescriptionPrefix
) : global::Daml.Runtime.Data.IDamlRecord<AnsRulesConfig>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("renewalDuration", RenewalDuration.ToRecord()),
        global::Daml.Runtime.Data.DamlField.Create("entryLifetime", EntryLifetime.ToRecord()),
        global::Daml.Runtime.Data.DamlField.Create("entryFee", new global::Daml.Runtime.Data.DamlNumeric(EntryFee)),
        global::Daml.Runtime.Data.DamlField.Create("descriptionPrefix", new global::Daml.Runtime.Data.DamlText(DescriptionPrefix))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsRulesConfig FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AnsRulesConfig(
        RenewalDuration: global::Daml.Runtime.Stdlib.RelTime.FromRecord(record.GetRequiredField("renewalDuration").As<global::Daml.Runtime.Data.DamlRecord>()),
        EntryLifetime: global::Daml.Runtime.Stdlib.RelTime.FromRecord(record.GetRequiredField("entryLifetime").As<global::Daml.Runtime.Data.DamlRecord>()),
        EntryFee: record.GetRequiredField("entryFee").As<global::Daml.Runtime.Data.DamlNumeric>().Value,
        DescriptionPrefix: record.GetRequiredField("descriptionPrefix").As<global::Daml.Runtime.Data.DamlText>().Value
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("renewalDuration", global::Daml.Runtime.Stdlib.RelTime.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "renewalDuration"), context.Field("renewalDuration"))),
            global::Daml.Runtime.Data.DamlField.Create("entryLifetime", global::Daml.Runtime.Stdlib.RelTime.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "entryLifetime"), context.Field("entryLifetime"))),
            global::Daml.Runtime.Data.DamlField.Create("entryFee", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadNumeric(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "entryFee"), context.Field("entryFee"))),
            global::Daml.Runtime.Data.DamlField.Create("descriptionPrefix", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "descriptionPrefix"), context.Field("descriptionPrefix")))
        );
    }

}
