// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml template Splice.Ans:AnsRules
/// </summary>
public sealed partial record AnsRules(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("dso")] global::Daml.Runtime.Data.Party Dso,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("config")] global::Splice.Ans.AnsRulesConfig Config
) : global::Daml.Runtime.Contracts.ITemplate, global::Daml.Runtime.Contracts.IHasChoices<AnsRules>, global::Daml.Runtime.Data.IDamlRecord<AnsRules>
{
    /// <summary>Gets the template identifier.</summary>
    public static global::Daml.Runtime.Data.Identifier TemplateId { get; } = new("cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1", "Splice.Ans", "AnsRules");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-amulet-name-service";

    /// <summary>Gets the package version.</summary>
    public static global::System.Version PackageVersion { get; } = new(0, 1, 24);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static global::Daml.Runtime.Contracts.DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, global::Daml.Runtime.Contracts.DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("dso", Dso.ToDamlValue()),
        global::Daml.Runtime.Data.DamlField.Create("config", Config.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsRules FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AnsRules(
        Dso: global::Daml.Runtime.Data.Party.FromDamlValue(record.GetRequiredField("dso").As<global::Daml.Runtime.Data.DamlParty>()),
        Config: global::Splice.Ans.AnsRulesConfig.FromRecord(record.GetRequiredField("config").As<global::Daml.Runtime.Data.DamlRecord>())
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("dso", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "dso"), context.Field("dso"))),
            global::Daml.Runtime.Data.DamlField.Create("config", global::Splice.Ans.AnsRulesConfig.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "config"), context.Field("config")))
        );
    }

    /// <summary>
    /// Exercise the AnsRules_CollectEntryRenewalPayment choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsRules, AnsRules_CollectEntryRenewalPayment, global::Splice.Ans.AnsRules_CollectEntryRenewalPaymentResult> ChoiceAnsRules_CollectEntryRenewalPayment { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AnsRules_CollectEntryRenewalPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsRules_CollectEntryRenewalPayment.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AnsRules_CollectEntryRenewalPaymentResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AnsRules.AnsRules_CollectEntryRenewalPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AnsRules_CollectEntryRenewalPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsRules_CollectInitialEntryPayment choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsRules, AnsRules_CollectInitialEntryPayment, global::Splice.Ans.AnsRules_CollectInitialEntryPaymentResult> ChoiceAnsRules_CollectInitialEntryPayment { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AnsRules_CollectInitialEntryPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsRules_CollectInitialEntryPayment.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AnsRules_CollectInitialEntryPaymentResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AnsRules.AnsRules_CollectInitialEntryPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AnsRules_CollectInitialEntryPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsRules_RejectEntryInitialPayment choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsRules, AnsRules_RejectEntryInitialPayment, global::Splice.Ans.AnsRules_RejectEntryInitialPaymentResult> ChoiceAnsRules_RejectEntryInitialPayment { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AnsRules_RejectEntryInitialPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsRules_RejectEntryInitialPayment.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AnsRules_RejectEntryInitialPaymentResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AnsRules.AnsRules_RejectEntryInitialPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AnsRules_RejectEntryInitialPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsRules_RequestEntry choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsRules, AnsRules_RequestEntry, global::Splice.Ans.AnsRules_RequestEntryResult> ChoiceAnsRules_RequestEntry { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AnsRules_RequestEntry"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsRules_RequestEntry.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AnsRules_RequestEntryResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AnsRules.AnsRules_RequestEntry.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AnsRules_RequestEntryResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AnsRules, global::Daml.Runtime.Data.DamlUnit, global::Daml.Runtime.Data.DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => global::Daml.Runtime.Data.DamlRecord.Create(),
        ArgumentDecoder = val => val is global::Daml.Runtime.Data.DamlRecord { Fields.Count: 0 } ? global::Daml.Runtime.Data.DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => global::Daml.Runtime.Data.DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return global::Daml.Runtime.Data.DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    public static global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Commands.IChoice> Choices { get; } = [ChoiceAnsRules_CollectEntryRenewalPayment, ChoiceAnsRules_CollectInitialEntryPayment, ChoiceAnsRules_RejectEntryInitialPayment, ChoiceAnsRules_RequestEntry, ChoiceArchive];

}


/// <summary>
/// Typed-submitter extensions for <see cref="AnsRules"/>. The
/// <see cref="TryCreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class AnsRulesSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="AnsRules"/> contract on the ledger.
    /// The submitting parties are derived from the payload — each Daml signatory is
    /// a reference to a payload field, so the caller never restates a party that's
    /// already in the record.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Contracts.ContractId<AnsRules>>> TryCreateAsync(
        this global::Daml.Ledger.Abstractions.ILedgerWriter client,
        AnsRules payload,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);
        global::System.ArgumentNullException.ThrowIfNull(payload);

        global::Daml.Runtime.Commands.SubmitterInfo submitter = payload.Dso;

        return global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TryCreateAsync<AnsRules>(client, payload, submitter, configure: configure, cancellationToken: cancellationToken);
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="global::Splice.Ans.AnsRules"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>SingleCommandExtensions.TrySubmitSingleAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class AnsRulesNonContractExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsRules_CollectEntryRenewalPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AnsRules_CollectEntryRenewalPaymentCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Splice.Ans.AnsRules.AnsRules_CollectEntryRenewalPayment argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsRules.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AnsRules_CollectEntryRenewalPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsRules_CollectEntryRenewalPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AnsRules_CollectEntryRenewalPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsRules_CollectEntryRenewalPaymentResult>> TryAnsRules_CollectEntryRenewalPaymentAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AnsRules.AnsRules_CollectEntryRenewalPayment argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsRules_CollectEntryRenewalPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsRules_CollectEntryRenewalPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsRules_CollectInitialEntryPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AnsRules_CollectInitialEntryPaymentCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Splice.Ans.AnsRules.AnsRules_CollectInitialEntryPayment argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsRules.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AnsRules_CollectInitialEntryPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsRules_CollectInitialEntryPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AnsRules_CollectInitialEntryPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsRules_CollectInitialEntryPaymentResult>> TryAnsRules_CollectInitialEntryPaymentAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AnsRules.AnsRules_CollectInitialEntryPayment argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsRules_CollectInitialEntryPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsRules_CollectInitialEntryPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsRules_RejectEntryInitialPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AnsRules_RejectEntryInitialPaymentCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Splice.Ans.AnsRules.AnsRules_RejectEntryInitialPayment argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsRules.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AnsRules_RejectEntryInitialPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsRules_RejectEntryInitialPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AnsRules_RejectEntryInitialPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsRules_RejectEntryInitialPaymentResult>> TryAnsRules_RejectEntryInitialPaymentAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AnsRules.AnsRules_RejectEntryInitialPayment argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsRules_RejectEntryInitialPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsRules_RejectEntryInitialPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsRules_RequestEntry choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AnsRules_RequestEntryCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Splice.Ans.AnsRules.AnsRules_RequestEntry argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsRules.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AnsRules_RequestEntry"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsRules_RequestEntry choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AnsRules_RequestEntryResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsRules_RequestEntryResult>> TryAnsRules_RequestEntryAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AnsRules.AnsRules_RequestEntry argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsRules_RequestEntryCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsRules_RequestEntryResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Archive choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand ArchiveCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AnsRules.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("Archive"),
            global::Daml.Runtime.Data.DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the Archive choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Daml.Runtime.Data.DamlUnit</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit>> TryArchiveAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AnsRules> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsRules_CollectEntryRenewalPaymentResult> ProjectAnsRules_CollectEntryRenewalPaymentResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsRules.ChoiceAnsRules_CollectEntryRenewalPayment, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsRules_CollectInitialEntryPaymentResult> ProjectAnsRules_CollectInitialEntryPaymentResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsRules.ChoiceAnsRules_CollectInitialEntryPayment, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsRules_RejectEntryInitialPaymentResult> ProjectAnsRules_RejectEntryInitialPaymentResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsRules.ChoiceAnsRules_RejectEntryInitialPayment, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AnsRules_RequestEntryResult> ProjectAnsRules_RequestEntryResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsRules.ChoiceAnsRules_RequestEntry, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit> ProjectArchiveResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AnsRules.ChoiceArchive, contractId);
}
