// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace Splice.Ans;

internal static class PackageRegistration_cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register()
    {
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Splice.Ans.AnsEntry>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Ans.AnsEntry>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Splice.Ans.AnsEntryContext>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Ans.AnsEntryContext>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Splice.Ans.AnsRules>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Ans.AnsRules>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed>();
    }
}
