// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Api.Token.AllocationRequestV2;

/// <summary>
/// Generated from Daml interface Splice.Api.Token.AllocationRequestV2:AllocationRequest
/// </summary>
/// <remarks>
/// Instance properties mirror the fields of the interface view <see cref="global::Splice.Api.Token.AllocationRequestV2.AllocationRequestView"/>,
/// which implements this marker, so a view can be read through a marker-typed variable.
/// <c>==</c> between marker-typed variables compares by reference equality; view payloads
/// materialize as concrete <see cref="global::Splice.Api.Token.AllocationRequestV2.AllocationRequestView"/> values, whose record value equality
/// applies once concretely typed.
/// </remarks>
public interface IAllocationRequest : global::Daml.Runtime.Contracts.IDamlInterface, global::Daml.Runtime.Contracts.IHasView<global::Splice.Api.Token.AllocationRequestV2.AllocationRequestView>, global::Daml.Runtime.Contracts.IHasChoices<IAllocationRequest>
{
    /// <summary>Gets the interface identifier.</summary>
    static global::Daml.Runtime.Data.Identifier global::Daml.Runtime.Contracts.IDamlInterface.InterfaceId => InterfaceId;

    /// <summary>Gets the interface identifier.</summary>
    public static new global::Daml.Runtime.Data.Identifier InterfaceId { get; } = new("adc16315a8943a8433886694720a2a000ae84c2315c4414bd6d0db4d1660de9c", "Splice.Api.Token.AllocationRequestV2", "AllocationRequest");

    /// <summary>Gets the package ID.</summary>
    static string global::Daml.Runtime.Contracts.IDamlInterface.PackageId => "adc16315a8943a8433886694720a2a000ae84c2315c4414bd6d0db4d1660de9c";

    /// <summary>Gets the package name.</summary>
    static string global::Daml.Runtime.Contracts.IDamlInterface.PackageName => "splice-api-token-allocation-request-v2";

    /// <summary>Gets the package version.</summary>
    static global::System.Version global::Daml.Runtime.Contracts.IDamlInterface.PackageVersion => new(1, 0, 0);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    static global::Daml.Runtime.Contracts.DamlTypeDescriptor global::Daml.Runtime.IDamlType.DamlTypeId => new(new global::Daml.Runtime.Data.Identifier("adc16315a8943a8433886694720a2a000ae84c2315c4414bd6d0db4d1660de9c", "Splice.Api.Token.AllocationRequestV2", "AllocationRequest"), global::Daml.Runtime.Contracts.DamlTypeKind.Interface, "splice-api-token-allocation-request-v2");

    /// <summary>Gets the pure type witness pairing this marker with its view record <see cref="global::Splice.Api.Token.AllocationRequestV2.AllocationRequestView"/>; passing it to a generic method infers both type parameters from one argument.</summary>
    public static global::Daml.Runtime.Contracts.ViewDescriptor<IAllocationRequest, global::Splice.Api.Token.AllocationRequestV2.AllocationRequestView> View { get; } = new();

    /// <summary>Gets the originalRequestCid field of the interface view.</summary>
    global::Daml.Runtime.Contracts.ContractId<global::Splice.Api.Token.AllocationRequestV2.IAllocationRequest>? OriginalRequestCid { get; }

    /// <summary>Gets the settlement field of the interface view.</summary>
    global::Splice.Api.Token.AllocationV2.SettlementInfo Settlement { get; }

    /// <summary>Gets the allocations field of the interface view.</summary>
    global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.Token.AllocationV2.AllocationSpecification> Allocations { get; }

    /// <summary>Gets the requestedAt field of the interface view.</summary>
    global::System.DateTimeOffset RequestedAt { get; }

    /// <summary>Gets the settleAt field of the interface view.</summary>
    global::System.DateTimeOffset? SettleAt { get; }

    /// <summary>Gets the availableActions field of the interface view.</summary>
    global::System.Collections.Generic.IReadOnlyDictionary<global::Splice.Api.Token.AllocationRequestV2.AllocationRequestAction, global::System.Collections.Generic.IReadOnlyList<global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party>>> AvailableActions { get; }

    /// <summary>Gets the meta field of the interface view.</summary>
    global::Splice.Api.Token.MetadataV1.Metadata Meta { get; }

    /// <summary>
    /// Exercise the AllocationRequest_Accept choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<IAllocationRequest, global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Accept, global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_AcceptResult> ChoiceAllocationRequest_Accept { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AllocationRequest_Accept"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Accept.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_AcceptResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Accept.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_AcceptResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AllocationRequest_Reject choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<IAllocationRequest, global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Reject, global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_RejectResult> ChoiceAllocationRequest_Reject { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AllocationRequest_Reject"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Reject.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_RejectResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Reject.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_RejectResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AllocationRequest_Withdraw choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<IAllocationRequest, global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Withdraw, global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_WithdrawResult> ChoiceAllocationRequest_Withdraw { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AllocationRequest_Withdraw"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Withdraw.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_WithdrawResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Withdraw.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_WithdrawResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<IAllocationRequest, global::Daml.Runtime.Data.DamlUnit, global::Daml.Runtime.Data.DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => global::Daml.Runtime.Data.DamlRecord.Create(),
        ArgumentDecoder = val => val is global::Daml.Runtime.Data.DamlRecord { Fields.Count: 0 } ? global::Daml.Runtime.Data.DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => global::Daml.Runtime.Data.DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return global::Daml.Runtime.Data.DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    static global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Commands.IChoice> global::Daml.Runtime.Contracts.IHasChoices<IAllocationRequest>.Choices { get; } = [ChoiceAllocationRequest_Accept, ChoiceAllocationRequest_Reject, ChoiceAllocationRequest_Withdraw, ChoiceArchive];

}

/// <summary>
/// Static <c>Try&lt;Choice&gt;Async</c> extension methods for the <c>AllocationRequest</c> Daml interface.
/// One method per choice; each submits an interface-typed
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> built via
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand.For{TOwner}(global::Daml.Runtime.Contracts.ContractId{TOwner},global::Daml.Runtime.Commands.ChoiceName,global::Daml.Runtime.Data.DamlValue)"/>
/// through <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
/// and projects the committed transaction's matching exercise event through the choice
/// descriptor's <c>ResultDecoder</c>, surfacing a typed
/// <see cref="global::Daml.Runtime.Outcomes.ExerciseOutcome{TResult}"/> — the choice's own return
/// type, not the implementing template's. A decode failure after a successful commit
/// surfaces as <see cref="global::Daml.Runtime.Outcomes.ExerciseOutcome{TResult}.CommittedUndecodable"/>,
/// never as a resubmittable error.
/// </summary>
public static class IAllocationRequestExtensions
{
    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>AllocationRequest_Accept</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AllocationRequest_AcceptCommand(
        this global::Daml.Runtime.Contracts.ContractId<IAllocationRequest> contractId,
        global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Accept argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return global::Daml.Runtime.Commands.ExerciseCommand.For<IAllocationRequest>(contractId, new global::Daml.Runtime.Commands.ChoiceName("AllocationRequest_Accept"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>AllocationRequest_Accept</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceAllocationRequest_Accept.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_AcceptResult>> TryAllocationRequest_AcceptAsync(
        this global::Daml.Runtime.Contracts.ContractId<IAllocationRequest> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Accept argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AllocationRequest_AcceptCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAllocationRequest_AcceptResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>AllocationRequest_Reject</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AllocationRequest_RejectCommand(
        this global::Daml.Runtime.Contracts.ContractId<IAllocationRequest> contractId,
        global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Reject argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return global::Daml.Runtime.Commands.ExerciseCommand.For<IAllocationRequest>(contractId, new global::Daml.Runtime.Commands.ChoiceName("AllocationRequest_Reject"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>AllocationRequest_Reject</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceAllocationRequest_Reject.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_RejectResult>> TryAllocationRequest_RejectAsync(
        this global::Daml.Runtime.Contracts.ContractId<IAllocationRequest> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Reject argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AllocationRequest_RejectCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAllocationRequest_RejectResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>AllocationRequest_Withdraw</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AllocationRequest_WithdrawCommand(
        this global::Daml.Runtime.Contracts.ContractId<IAllocationRequest> contractId,
        global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Withdraw argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return global::Daml.Runtime.Commands.ExerciseCommand.For<IAllocationRequest>(contractId, new global::Daml.Runtime.Commands.ChoiceName("AllocationRequest_Withdraw"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>AllocationRequest_Withdraw</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceAllocationRequest_Withdraw.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_WithdrawResult>> TryAllocationRequest_WithdrawAsync(
        this global::Daml.Runtime.Contracts.ContractId<IAllocationRequest> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Withdraw argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AllocationRequest_WithdrawCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAllocationRequest_WithdrawResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>Archive</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand ArchiveCommand(
        this global::Daml.Runtime.Contracts.ContractId<IAllocationRequest> contractId)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        return global::Daml.Runtime.Commands.ExerciseCommand.For<IAllocationRequest>(contractId, new global::Daml.Runtime.Commands.ChoiceName("Archive"), global::Daml.Runtime.Data.DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the <c>Archive</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceArchive.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit>> TryArchiveAsync(
        this global::Daml.Runtime.Contracts.ContractId<IAllocationRequest> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_AcceptResult> ProjectAllocationRequest_AcceptResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(IAllocationRequest.ChoiceAllocationRequest_Accept, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_RejectResult> ProjectAllocationRequest_RejectResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(IAllocationRequest.ChoiceAllocationRequest_Reject, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_WithdrawResult> ProjectAllocationRequest_WithdrawResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(IAllocationRequest.ChoiceAllocationRequest_Withdraw, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit> ProjectArchiveResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(IAllocationRequest.ChoiceArchive, contractId);
}
