// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace Splice.Api.Token.MetadataV1;

internal static class PackageRegistration_4ded6b668cb3b64f7a88a30874cd41c75829f5e064b3fbbadf41ec7e8363354f
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register()
    {
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Api.Token.MetadataV1.IAnyContract>();
    }
}
