// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Ans.AmuletConversionRateFeed;

/// <summary>
/// Generated from Daml record AmuletConversionRateFeed_UpdateResult
/// </summary>
public sealed record AmuletConversionRateFeed_UpdateResult(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("cid")] global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed> Cid
) : global::Daml.Runtime.Data.IDamlRecord<AmuletConversionRateFeed_UpdateResult>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("cid", Cid.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AmuletConversionRateFeed_UpdateResult FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AmuletConversionRateFeed_UpdateResult(
        Cid: new global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed>(record.GetRequiredField("cid").As<global::Daml.Runtime.Contracts.DamlContractId>().Value)
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("cid", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "cid"), context.Field("cid")))
        );
    }

}
