// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Ans.AmuletConversionRateFeed;

/// <summary>
/// Generated from Daml template Splice.Ans.AmuletConversionRateFeed:AmuletConversionRateFeed
/// </summary>
public sealed partial record AmuletConversionRateFeed(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("publisher")] global::Daml.Runtime.Data.Party Publisher,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("dso")] global::Daml.Runtime.Data.Party Dso,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("nextUpdateAfter")] global::System.DateTimeOffset? NextUpdateAfter,
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("amuletConversionRate")] decimal AmuletConversionRate
) : global::Daml.Runtime.Contracts.ITemplate, global::Daml.Runtime.Contracts.IHasChoices<AmuletConversionRateFeed>, global::Daml.Runtime.Data.IDamlRecord<AmuletConversionRateFeed>
{
    /// <summary>Gets the template identifier.</summary>
    public static global::Daml.Runtime.Data.Identifier TemplateId { get; } = new("cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1", "Splice.Ans.AmuletConversionRateFeed", "AmuletConversionRateFeed");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-amulet-name-service";

    /// <summary>Gets the package version.</summary>
    public static global::System.Version PackageVersion { get; } = new(0, 1, 24);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static global::Daml.Runtime.Contracts.DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, global::Daml.Runtime.Contracts.DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("publisher", Publisher.ToDamlValue()),
        global::Daml.Runtime.Data.DamlField.Create("dso", Dso.ToDamlValue()),
        global::Daml.Runtime.Data.DamlField.Create("nextUpdateAfter", NextUpdateAfter is { } __NextUpdateAfter ? new global::Daml.Runtime.Data.DamlOptional(new global::Daml.Runtime.Data.DamlTimestamp(__NextUpdateAfter)) : global::Daml.Runtime.Data.DamlOptional.None),
        global::Daml.Runtime.Data.DamlField.Create("amuletConversionRate", new global::Daml.Runtime.Data.DamlNumeric(AmuletConversionRate))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AmuletConversionRateFeed FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AmuletConversionRateFeed(
        Publisher: global::Daml.Runtime.Data.Party.FromDamlValue(record.GetRequiredField("publisher").As<global::Daml.Runtime.Data.DamlParty>()),
        Dso: global::Daml.Runtime.Data.Party.FromDamlValue(record.GetRequiredField("dso").As<global::Daml.Runtime.Data.DamlParty>()),
        NextUpdateAfter: record.GetOptionalField("nextUpdateAfter").AsOptional().HasValue ? record.GetOptionalField("nextUpdateAfter").AsOptional().Value!.As<global::Daml.Runtime.Data.DamlTimestamp>().Value : null,
        AmuletConversionRate: record.GetRequiredField("amuletConversionRate").As<global::Daml.Runtime.Data.DamlNumeric>().Value
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        var fields = new global::System.Collections.Generic.List<global::Daml.Runtime.Data.DamlField>(4);
        fields.Add(global::Daml.Runtime.Data.DamlField.Create("publisher", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "publisher"), context.Field("publisher"))));
        fields.Add(global::Daml.Runtime.Data.DamlField.Create("dso", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "dso"), context.Field("dso"))));
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.AddFieldIfPresent(fields, json, "nextUpdateAfter", present => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadOptional(present, context.Field("nextUpdateAfter"), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadTimestamp(__json0, __ctx0)));
        fields.Add(global::Daml.Runtime.Data.DamlField.Create("amuletConversionRate", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadNumeric(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "amuletConversionRate"), context.Field("amuletConversionRate"))));
        return global::Daml.Runtime.Data.DamlRecord.Create(fields.ToArray());
    }

    /// <summary>
    /// Exercise the AmuletConversionRateFeed_ArchiveAsDso choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AmuletConversionRateFeed, AmuletConversionRateFeed_ArchiveAsDso, global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResult> ChoiceAmuletConversionRateFeed_ArchiveAsDso { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AmuletConversionRateFeed_ArchiveAsDso"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AmuletConversionRateFeed_ArchiveAsDso.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResultExtensions.FromDamlEnum(val.As<global::Daml.Runtime.Data.DamlEnum>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDso.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResultExtensions.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AmuletConversionRateFeed_Update choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AmuletConversionRateFeed, AmuletConversionRateFeed_Update, global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_UpdateResult> ChoiceAmuletConversionRateFeed_Update { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("AmuletConversionRateFeed_Update"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AmuletConversionRateFeed_Update.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_UpdateResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.AmuletConversionRateFeed_Update.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_UpdateResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<AmuletConversionRateFeed, global::Daml.Runtime.Data.DamlUnit, global::Daml.Runtime.Data.DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => global::Daml.Runtime.Data.DamlRecord.Create(),
        ArgumentDecoder = val => val is global::Daml.Runtime.Data.DamlRecord { Fields.Count: 0 } ? global::Daml.Runtime.Data.DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => global::Daml.Runtime.Data.DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return global::Daml.Runtime.Data.DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    public static global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Commands.IChoice> Choices { get; } = [ChoiceAmuletConversionRateFeed_ArchiveAsDso, ChoiceAmuletConversionRateFeed_Update, ChoiceArchive];

}


/// <summary>
/// Typed-submitter extensions for <see cref="AmuletConversionRateFeed"/>. The
/// <see cref="TryCreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class AmuletConversionRateFeedSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="AmuletConversionRateFeed"/> contract on the ledger.
    /// The submitting parties are derived from the payload — each Daml signatory is
    /// a reference to a payload field, so the caller never restates a party that's
    /// already in the record.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Contracts.ContractId<AmuletConversionRateFeed>>> TryCreateAsync(
        this global::Daml.Ledger.Abstractions.ILedgerWriter client,
        AmuletConversionRateFeed payload,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);
        global::System.ArgumentNullException.ThrowIfNull(payload);

        global::Daml.Runtime.Commands.SubmitterInfo submitter = payload.Publisher;

        return global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TryCreateAsync<AmuletConversionRateFeed>(client, payload, submitter, configure: configure, cancellationToken: cancellationToken);
    }

    /// <summary>
    /// Returns the observers of a <see cref="AmuletConversionRateFeed"/> payload —
    /// the parties named in the Daml <c>observer</c> clause, derived from
    /// the payload's <c>Party</c> properties in declaration order. Useful
    /// for inspecting / asserting the observer set without exercising a
    /// choice.
    /// </summary>
    /// <param name="payload">The contract payload.</param>
    public static global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party> Observers(AmuletConversionRateFeed payload)
    {
        global::System.ArgumentNullException.ThrowIfNull(payload);
        return new global::Daml.Runtime.Data.Party[]
        {
            payload.Dso
        };
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>SingleCommandExtensions.TrySubmitSingleAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class AmuletConversionRateFeedNonContractExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AmuletConversionRateFeed_ArchiveAsDso choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AmuletConversionRateFeed_ArchiveAsDsoCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed> contractId,
        global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDso argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AmuletConversionRateFeed_ArchiveAsDso"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AmuletConversionRateFeed_ArchiveAsDso choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResult>> TryAmuletConversionRateFeed_ArchiveAsDsoAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDso argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AmuletConversionRateFeed_ArchiveAsDsoCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAmuletConversionRateFeed_ArchiveAsDsoResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AmuletConversionRateFeed_Update choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand AmuletConversionRateFeed_UpdateCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed> contractId,
        global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.AmuletConversionRateFeed_Update argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("AmuletConversionRateFeed_Update"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AmuletConversionRateFeed_Update choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_UpdateResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_UpdateResult>> TryAmuletConversionRateFeed_UpdateAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.AmuletConversionRateFeed_Update argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AmuletConversionRateFeed_UpdateCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAmuletConversionRateFeed_UpdateResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Archive choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand ArchiveCommand(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed> contractId)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        return new global::Daml.Runtime.Commands.ExerciseCommand(
            global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.TemplateId,
            contractId,
            new global::Daml.Runtime.Commands.ChoiceName("Archive"),
            global::Daml.Runtime.Data.DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the Archive choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>global::Daml.Runtime.Data.DamlUnit</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit>> TryArchiveAsync(
        this global::Daml.Runtime.Contracts.ContractId<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResult> ProjectAmuletConversionRateFeed_ArchiveAsDsoResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.ChoiceAmuletConversionRateFeed_ArchiveAsDso, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_UpdateResult> ProjectAmuletConversionRateFeed_UpdateResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.ChoiceAmuletConversionRateFeed_Update, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit> ProjectArchiveResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed.ChoiceArchive, contractId);
}
