// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;

namespace Splice.Ans.AmuletConversionRateFeed;

/// <summary>
/// Generated from Daml enum AmuletConversionRateFeed_ArchiveAsDsoResult
/// </summary>
public enum AmuletConversionRateFeed_ArchiveAsDsoResult
{
    /// <summary>AmuletConversionRateFeed_ArchiveAsDsoResult enum constructor.</summary>
    AmuletConversionRateFeed_ArchiveAsDsoResult,
}

/// <summary>
/// Extension methods for AmuletConversionRateFeed_ArchiveAsDsoResult serialization.
/// </summary>
public static class AmuletConversionRateFeed_ArchiveAsDsoResultExtensions
{
    /// <summary>Converts to a DamlEnum value.</summary>
    public static global::Daml.Runtime.Data.DamlEnum ToDamlEnum(this global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResult value)
    {
        return value switch
        {
            global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResult.AmuletConversionRateFeed_ArchiveAsDsoResult => global::Daml.Runtime.Data.DamlEnum.Create("AmuletConversionRateFeed_ArchiveAsDsoResult"),
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(value), value, null)
        };
    }

    /// <summary>Creates an instance from a DamlEnum value.</summary>
    public static global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResult FromDamlEnum(global::Daml.Runtime.Data.DamlEnum value)
    {
        return value.Constructor switch
        {
            "AmuletConversionRateFeed_ArchiveAsDsoResult" => global::Splice.Ans.AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDsoResult.AmuletConversionRateFeed_ArchiveAsDsoResult,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(value), value.Constructor, null)
        };
    }

    /// <summary>Decodes a Daml-LF JSON enum constructor directly into a DamlEnum, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlEnum __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context) =>
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadEnumConstructor(json, context, ExpectedConstructors);

    private static readonly string[] ExpectedConstructors = ["AmuletConversionRateFeed_ArchiveAsDsoResult"];

}
