// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Ans.AmuletConversionRateFeed;

/// <summary>
/// Generated from Daml record MarkerContext
/// </summary>
public sealed record MarkerContext(
    global::Daml.Runtime.Contracts.ContractId<global::Splice.Api.FeaturedAppRightV1.IFeaturedAppRight> FeaturedAppRightCid,
    global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary> Beneficiaries
) : global::Daml.Runtime.Data.IDamlRecord<MarkerContext>
{
    /// <summary>The Daml field <c>featuredAppRightCid</c>.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("featuredAppRightCid")]
    public global::Daml.Runtime.Contracts.ContractId<global::Splice.Api.FeaturedAppRightV1.IFeaturedAppRight> FeaturedAppRightCid { get; init; } = FeaturedAppRightCid;

    private readonly global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary> _beneficiaries = global::Daml.Runtime.Data.DamlFieldCollections.Copy(Beneficiaries);

    /// <summary>The Daml field <c>beneficiaries</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("beneficiaries")]
    public global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary> Beneficiaries
    {
        get => _beneficiaries;
        init => _beneficiaries = global::Daml.Runtime.Data.DamlFieldCollections.Copy(value);
    }

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(MarkerContext? other) =>
        other is not null
        && global::System.Collections.Generic.EqualityComparer<global::Daml.Runtime.Contracts.ContractId<global::Splice.Api.FeaturedAppRightV1.IFeaturedAppRight>>.Default.Equals(FeaturedAppRightCid, other.FeaturedAppRightCid)
        && global::Daml.Runtime.Data.DamlFieldCollections.Equal(Beneficiaries, other.Beneficiaries);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(FeaturedAppRightCid);
        hash.Add(global::Daml.Runtime.Data.DamlFieldCollections.Hash(Beneficiaries));
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("featuredAppRightCid", FeaturedAppRightCid.ToDamlValue()),
        global::Daml.Runtime.Data.DamlField.Create("beneficiaries", new global::Daml.Runtime.Data.DamlList(Beneficiaries.Select(x => (global::Daml.Runtime.Data.DamlValue)x.ToRecord()).ToList()))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static MarkerContext FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new MarkerContext(
        FeaturedAppRightCid: new global::Daml.Runtime.Contracts.ContractId<global::Splice.Api.FeaturedAppRightV1.IFeaturedAppRight>(record.GetRequiredField("featuredAppRightCid").As<global::Daml.Runtime.Contracts.DamlContractId>().Value),
        Beneficiaries: (global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary>)record.GetRequiredField("beneficiaries").As<global::Daml.Runtime.Data.DamlList>().Values.Select(x => global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary.FromRecord(x.As<global::Daml.Runtime.Data.DamlRecord>())).ToList()
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("featuredAppRightCid", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "featuredAppRightCid"), context.Field("featuredAppRightCid"))),
            global::Daml.Runtime.Data.DamlField.Create("beneficiaries", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "beneficiaries"), context.Field("beneficiaries"), (__json0, __ctx0) => global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary.__ReadDamlLfJson(__json0, __ctx0)))
        );
    }

}
