// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Api.Token.AllocationInstructionV2;

/// <summary>
/// Generated from Daml record AllocationInstructionResult_Output.AllocationInstructionResult_Completed
/// </summary>
public sealed record AllocationInstructionResult_Output_AllocationInstructionResult_Completed(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("allocationCid")] global::Daml.Runtime.Contracts.ContractId<global::Splice.Api.Token.AllocationV2.IAllocation> AllocationCid
) : global::Daml.Runtime.Data.IDamlRecord<AllocationInstructionResult_Output_AllocationInstructionResult_Completed>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("allocationCid", AllocationCid.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationInstructionResult_Output_AllocationInstructionResult_Completed FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AllocationInstructionResult_Output_AllocationInstructionResult_Completed(
        AllocationCid: new global::Daml.Runtime.Contracts.ContractId<global::Splice.Api.Token.AllocationV2.IAllocation>(record.GetRequiredField("allocationCid").As<global::Daml.Runtime.Contracts.DamlContractId>().Value)
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("allocationCid", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "allocationCid"), context.Field("allocationCid")))
        );
    }

}
