// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace Splice.Api.Token.AllocationInstructionV2;

internal static class PackageRegistration_9818a0b5b827109de03a04c8f6151cde9d1e7fe5123dbb2dfeb0e52d7271287c
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register()
    {
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Api.Token.AllocationInstructionV2.IAllocationFactory>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Api.Token.AllocationInstructionV2.IAllocationInstruction>();
    }
}
