// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace CollisionA;

public sealed partial record Agreement
{
    /// <summary>
    /// Choice argument type for Retag.
    /// </summary>
    public sealed record Retag(
        [property: global::Daml.Runtime.Data.DamlFieldAttribute("newOperator")] global::Daml.Runtime.Data.Party NewOperator
    ) : global::Daml.Runtime.Data.IDamlRecord<Retag>
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("newOperator", NewOperator.ToDamlValue())
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static Retag FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new Retag(
            NewOperator: global::Daml.Runtime.Data.Party.FromDamlValue(record.GetRequiredField("newOperator").As<global::Daml.Runtime.Data.DamlParty>())
        );

        /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return global::Daml.Runtime.Data.DamlRecord.Create(
                global::Daml.Runtime.Data.DamlField.Create("newOperator", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "newOperator"), context.Field("newOperator")))
            );
        }

    }
}
