// Copyright 2026 Peaceful Studio OÜ
// SPDX-License-Identifier: Apache-2.0

using System.Text.Json;
using AwesomeAssertions;
using Daml.Runtime.Data;
using Daml.Runtime.Serialization;
using Splice.Amulet;
using Splice.Fees;
using Splice.ValidatorLicense;
using Xunit;

namespace Canton.Ledger.Client.PublishedBindings.Tests;

/// <summary>
/// Decodes JSON Ledger API payloads through the pinned, already-published <c>Splice.Amulet</c>
/// binding, which was generated by an earlier codegen release than this checkout's runtime. A
/// published binding keeps calling the runtime members it was generated against, so removing one
/// breaks every consumer of the package until it is regenerated and republished. This is the only
/// project that references a published Splice package: the LocalNet parity suite reads Splice
/// contracts through bindings generated from the Splice DARs by this checkout's codegen. A change
/// that intentionally breaks published bindings updates the expectations here in the same pull
/// request, and the pins move to the newly published packages after each SDK release. The rows
/// named <c>documented_S2_break</c> pin the break the type-parameter absence change ships on
/// purpose: it changed <c>DamlRecord.GetTypeParameterField</c>, <c>DamlLfJsonDecoders.ReadTypeParameterField</c>, the
/// four-parameter <c>ReadTuple2</c> and <c>Tuple2.FromRecord</c> in place, so a binding published
/// before it fails with <see cref="MissingMethodException"/> until it is regenerated. <c>Tuple3.FromRecord</c>
/// and <c>ReadTuple3</c> change the same way, but no published Splice package references them. These
/// pins move after the next SDK release. The row named <c>documented_break</c> pins the removal of
/// <c>DamlLfJsonDecoders.OptionalField</c> and <c>OptionalChainField</c>: a binding published before
/// the generator stopped calling them fails with <see cref="MissingMethodException"/> until it is
/// regenerated.
/// </summary>
public sealed class PublishedSpliceBindingsCompatibilityTests
{
    private const string OnlyRequiredFields =
        """{"validator":"a-validator-1::1220aa","sponsor":"a-validator-1::1220aa","dso":"DSO::1220bb"}""";

    [Fact]
    public void ValidatorLicense_published_binding_fails_with_MissingMethodException_for_OptionalField_as_the_documented_break()
    {
        var act = () => DamlLfJsonReader.ReadRecord<ValidatorLicense>(OnlyRequiredFields);

        act.Should().Throw<MissingMethodException>().WithMessage("*OptionalField*");
    }

    [Fact]
    public void SteppedRate_published_binding_fails_with_MissingMethodException_for_ReadTuple2_as_the_documented_S2_break()
    {
        using var document = JsonDocument.Parse("""{"initialRate":"0.1","steps":[{"_1":"1","_2":"0.2"}]}""");

        var act = () => SteppedRate.__ReadDamlLfJson(document.RootElement, DamlLfJsonDecodeContext.Root("SteppedRate"));

        act.Should().Throw<MissingMethodException>().WithMessage("*ReadTuple2*");
    }

    [Fact]
    public void AmuletCreateSummary_published_binding_fails_with_MissingMethodException_for_ReadTypeParameterField_as_the_documented_S2_break()
    {
        using var document = JsonDocument.Parse("""{"amulet":"00ab","amuletPrice":"1","round":{"number":"1"}}""");

        var act = () => AmuletCreateSummary<string>.__ReadDamlLfJson(
            document.RootElement, DamlLfJsonDecodeContext.Root("AmuletCreateSummary"), DamlLfJsonDecoders.ReadText);

        act.Should().Throw<MissingMethodException>().WithMessage("*ReadTypeParameterField*");
    }

    [Fact]
    public void AmuletCreateSummary_published_binding_fails_with_MissingMethodException_for_GetTypeParameterField_as_the_documented_S2_break()
    {
        var record = DamlRecord.Create(
            DamlField.Create("amulet", new DamlText("00ab")),
            DamlField.Create("amuletPrice", new DamlNumeric(1m)),
            DamlField.Create("round", DamlRecord.Create(DamlField.Create("number", new DamlInt64(1)))));

        var act = () => AmuletCreateSummary<string>.FromRecord(record, value => value.As<DamlText>().Value);

        act.Should().Throw<MissingMethodException>().WithMessage("*GetTypeParameterField*");
    }

    [Fact]
    public void SteppedRate_published_binding_fails_with_MissingMethodException_for_Tuple2_FromRecord_as_the_documented_S2_break()
    {
        var step = DamlRecord.Create(
            DamlField.Create("_1", new DamlNumeric(1m)),
            DamlField.Create("_2", new DamlNumeric(0.2m)));
        var record = DamlRecord.Create(
            DamlField.Create("initialRate", new DamlNumeric(0.1m)),
            DamlField.Create("steps", DamlList.Create(step)));

        var act = () => SteppedRate.FromRecord(record);

        act.Should().Throw<MissingMethodException>().WithMessage("*Tuple2*FromRecord*");
    }
}
