// Copyright 2026 Peaceful Studio OÜ
// SPDX-License-Identifier: Apache-2.0

using AwesomeAssertions;
using Daml.Codegen.CSharp.CodeGen;
using Daml.Codegen.CSharp.Tests.TestHelpers;
using Daml.Codegen.Intermediate.Model;
using Xunit;
using static Daml.Codegen.CSharp.Tests.TestHelpers.GeneratorFactory;

namespace Daml.Codegen.CSharp.Tests;

public class PackageRegistrationEmitterTests
{
    private static DamlType Text => new DamlPrimitiveType(DamlPrimitive.Text);

    private static DamlType Unit => new DamlPrimitiveType(DamlPrimitive.Unit);

    private static DamlChoice Choice(string name) =>
        new() { Name = name, Consuming = false, ArgumentType = Unit, ReturnType = Unit };

    private static DamlTemplate Template(string name, DamlType? key = null) =>
        new() { Name = name, Choices = [Choice("Ping")], Key = key };

    private static DamlDataType Payload(string name) =>
        new() { Name = name, Definition = new DamlRecordDefinition([new DamlFieldDefinition("owner", new DamlPrimitiveType(DamlPrimitive.Party))]) };

    private static DamlInterface Interface(string name, params DamlChoice[] choices) =>
        new() { Name = name, Choices = choices };

    private static DamlModule Module(
        string name,
        IReadOnlyList<DamlTemplate>? templates = null,
        IReadOnlyList<DamlInterface>? interfaces = null,
        IReadOnlyList<DamlDataType>? extraDataTypes = null) =>
        new()
        {
            Name = name,
            Templates = templates ?? [],
            DataTypes = (templates ?? []).Select(template => Payload(template.Name)).Concat(extraDataTypes ?? []).ToList(),
            Interfaces = interfaces ?? [],
        };

    private static DamlPackage Package(string id, string name, params DamlModule[] modules) =>
        new()
        {
            PackageId = id,
            Name = name,
            Version = new Version(1, 0, 0),
            LfVersion = "2.1",
            Modules = modules,
            DependencyReferences = [],
        };

    private static IReadOnlyList<GeneratedFile> RegistrationFiles(IReadOnlyList<GeneratedFile> files) =>
        files.Where(file => file.RelativePath.Contains("PackageRegistration_", StringComparison.Ordinal)).ToList();

    private static string Lf(string text) => text.ReplaceLineEndings("\n");

    [Fact]
    public void Generate_registers_a_keyed_template_an_unkeyed_template_and_an_interface_with_choices()
    {
        var dar = new DarModel
        {
            MainPackage = Package(
                "pkgone",
                "main",
                Module(
                    "Test.Module",
                    templates: [Template("Asset", key: Text), Template("Note")],
                    interfaces: [Interface("Holding", Choice("Pass")), Interface("Plain")],
                    extraDataTypes: [Payload("Account")])),
            Dependencies = [],
        };

        var registration = RegistrationFiles(CreateGenerator().Generate(dar)).Should().ContainSingle().Which;

        registration.RelativePath.Should().Be("Test/Module/PackageRegistration_pkgone.cs");
        Lf(registration.Content).Should().Be(Lf("""
            // <auto-generated>
            // This code was generated by canton-dotnet-sdk.
            // Do not edit this file manually.
            // </auto-generated>

            #nullable enable

            namespace Test.Module;

            internal static class PackageRegistration_pkgone
            {
                [global::System.Runtime.CompilerServices.ModuleInitializer]
                internal static void Register()
                {
                    global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Test.Module.Asset>();
                    global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Test.Module.Asset>();
                    global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForKey<global::Test.Module.Asset, string>();
                    global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForRecord<global::Test.Module.Note>();
                    global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Test.Module.Note>();
                    global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Test.Module.IHolding>();
                }
            }

            """));
    }

    [Fact]
    public void Generate_spells_a_record_key_with_its_global_qualified_name()
    {
        var dar = new DarModel
        {
            MainPackage = Package(
                "pkgone",
                "main",
                Module("Test.Module", templates: [Template("Asset", key: new DamlTypeRef("", "Test.Module", "AssetKey"))], extraDataTypes: [Payload("AssetKey")])),
            Dependencies = [],
        };

        var registration = RegistrationFiles(CreateGenerator().Generate(dar)).Should().ContainSingle().Which;

        registration.Content.Should().Contain("ForKey<global::Test.Module.Asset, global::Test.Module.AssetKey>();");
    }

    [Fact]
    public void Generate_leaves_a_template_the_root_filter_excludes_unregistered()
    {
        var dar = new DarModel
        {
            MainPackage = Package(
                "pkgone",
                "main",
                Module("Test.Module", templates: [Template("Asset"), Template("Note", key: Text)], interfaces: [Interface("Holding", Choice("Pass"))])),
            Dependencies = [],
        };

        var files = CreateGenerator(new CodeGenOptions { RootFilter = "^Test.Module:Asset$" }).Generate(dar);

        var registration = RegistrationFiles(files).Should().ContainSingle().Which;
        registration.Content.Should().Contain("ForRecord<global::Test.Module.Asset>();");
        registration.Content.Should().NotContain("Note");
        registration.Content.Should().NotContain("IHolding");
    }

    [Fact]
    public void Generate_emits_no_registration_file_for_a_package_with_nothing_to_register()
    {
        var dar = new DarModel
        {
            MainPackage = Package(
                "pkgone",
                "main",
                Module("Test.Module", interfaces: [Interface("Plain")], extraDataTypes: [Payload("Person")])),
            Dependencies = [],
        };

        RegistrationFiles(CreateGenerator().Generate(dar)).Should().BeEmpty();
    }

    [Fact]
    public void Generate_emits_one_registration_file_per_package_for_a_main_package_and_its_dependency()
    {
        var dar = new DarModel
        {
            MainPackage = Package("mainid", "main", Module("Main.Module", templates: [Template("Asset")])),
            Dependencies = [Package("depid", "dep", Module("Dep.Module", templates: [Template("Loan")]))],
        };

        var files = CreateGenerator(new CodeGenOptions { IncludeDependencies = true, NamespacePrefix = "Acme" }).Generate(dar);

        RegistrationFiles(files).Select(file => file.RelativePath).Should().Equal(
            "Acme/Main/Module/PackageRegistration_mainid.cs",
            "Dep/Module/PackageRegistration_depid.cs");
    }

    [Fact]
    public void Generate_gives_two_package_ids_of_one_package_name_distinct_class_names()
    {
        DarModel DarOf(string packageId) => new()
        {
            MainPackage = Package(packageId, "same-name", Module("Test.Module", templates: [Template("Asset")])),
            Dependencies = [],
        };

        var first = RegistrationFiles(CreateGenerator().Generate(DarOf("aaaa"))).Single();
        var second = RegistrationFiles(CreateGenerator().Generate(DarOf("bbbb"))).Single();

        first.Content.Should().Contain("internal static class PackageRegistration_aaaa");
        second.Content.Should().Contain("internal static class PackageRegistration_bbbb");
    }

    [Fact]
    public void Generate_emits_the_registration_class_inside_a_block_scoped_namespace_when_file_scoped_namespaces_are_off()
    {
        var dar = new DarModel
        {
            MainPackage = Package("pkgone", "main", Module("Test.Module", templates: [Template("Asset")])),
            Dependencies = [],
        };

        var registration = RegistrationFiles(CreateGenerator(new CodeGenOptions { UseFileScopedNamespaces = false }).Generate(dar)).Single();

        Lf(registration.Content).Should().Contain(Lf("""
            namespace Test.Module
            {
                internal static class PackageRegistration_pkgone
                {
                    [global::System.Runtime.CompilerServices.ModuleInitializer]
                    internal static void Register()
                    {
            """));
    }
}
