// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Api.Token.TransferInstructionV2;

/// <summary>
/// Generated from Daml interface Splice.Api.Token.TransferInstructionV2:TransferFactory
/// </summary>
/// <remarks>
/// Instance properties mirror the fields of the interface view <see cref="global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView"/>,
/// which implements this marker, so a view can be read through a marker-typed variable.
/// <c>==</c> between marker-typed variables compares by reference equality; view payloads
/// materialize as concrete <see cref="global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView"/> values, whose record value equality
/// applies once concretely typed.
/// </remarks>
public interface ITransferFactory : global::Daml.Runtime.Contracts.IDamlInterface, global::Daml.Runtime.Contracts.IHasView<global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView>, global::Daml.Runtime.Contracts.IHasChoices<ITransferFactory>
{
    /// <summary>Gets the interface identifier.</summary>
    static global::Daml.Runtime.Data.Identifier global::Daml.Runtime.Contracts.IDamlInterface.InterfaceId => InterfaceId;

    /// <summary>Gets the interface identifier.</summary>
    public static new global::Daml.Runtime.Data.Identifier InterfaceId { get; } = new("29317e3b7b165d2bbf16721bcca0ec4869e53eddb2738bddf790d61af28e0099", "Splice.Api.Token.TransferInstructionV2", "TransferFactory");

    /// <summary>Gets the package ID.</summary>
    static string global::Daml.Runtime.Contracts.IDamlInterface.PackageId => "29317e3b7b165d2bbf16721bcca0ec4869e53eddb2738bddf790d61af28e0099";

    /// <summary>Gets the package name.</summary>
    static string global::Daml.Runtime.Contracts.IDamlInterface.PackageName => "splice-api-token-transfer-instruction-v2";

    /// <summary>Gets the package version.</summary>
    static global::System.Version global::Daml.Runtime.Contracts.IDamlInterface.PackageVersion => new(1, 0, 0);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    static global::Daml.Runtime.Contracts.DamlTypeDescriptor global::Daml.Runtime.IDamlType.DamlTypeId => new(new global::Daml.Runtime.Data.Identifier("29317e3b7b165d2bbf16721bcca0ec4869e53eddb2738bddf790d61af28e0099", "Splice.Api.Token.TransferInstructionV2", "TransferFactory"), global::Daml.Runtime.Contracts.DamlTypeKind.Interface, "splice-api-token-transfer-instruction-v2");

    /// <summary>Gets the pure type witness pairing this marker with its view record <see cref="global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView"/>; passing it to a generic method infers both type parameters from one argument.</summary>
    public static global::Daml.Runtime.Contracts.ViewDescriptor<ITransferFactory, global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView> View { get; } = new();

    /// <summary>Gets the admin field of the interface view.</summary>
    global::Daml.Runtime.Data.Party Admin { get; }

    /// <summary>Gets the meta field of the interface view.</summary>
    global::Splice.Api.Token.MetadataV1.Metadata Meta { get; }

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<ITransferFactory, global::Daml.Runtime.Data.DamlUnit, global::Daml.Runtime.Data.DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => global::Daml.Runtime.Data.DamlRecord.Create(),
        ArgumentDecoder = val => val is global::Daml.Runtime.Data.DamlRecord { Fields.Count: 0 } ? global::Daml.Runtime.Data.DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => global::Daml.Runtime.Data.DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return global::Daml.Runtime.Data.DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>
    /// Exercise the TransferFactory_PublicFetch choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<ITransferFactory, global::Splice.Api.Token.TransferInstructionV2.TransferFactory_PublicFetch, global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView> ChoiceTransferFactory_PublicFetch { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("TransferFactory_PublicFetch"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => global::Splice.Api.Token.TransferInstructionV2.TransferFactory_PublicFetch.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Api.Token.TransferInstructionV2.TransferFactory_PublicFetch.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the TransferFactory_Transfer choice.
    /// </summary>
    public static global::Daml.Runtime.Commands.Choice<ITransferFactory, global::Splice.Api.Token.TransferInstructionV2.TransferFactory_Transfer, global::Splice.Api.Token.TransferInstructionV2.TransferInstructionResult> ChoiceTransferFactory_Transfer { get; } = new()
    {
        Name = new global::Daml.Runtime.Commands.ChoiceName("TransferFactory_Transfer"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => global::Splice.Api.Token.TransferInstructionV2.TransferFactory_Transfer.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ResultDecoder = val => global::Splice.Api.Token.TransferInstructionV2.TransferInstructionResult.FromRecord(val.As<global::Daml.Runtime.Data.DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Api.Token.TransferInstructionV2.TransferFactory_Transfer.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Api.Token.TransferInstructionV2.TransferInstructionResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    static global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Commands.IChoice> global::Daml.Runtime.Contracts.IHasChoices<ITransferFactory>.Choices { get; } = [ChoiceArchive, ChoiceTransferFactory_PublicFetch, ChoiceTransferFactory_Transfer];

}

/// <summary>
/// Static <c>Try&lt;Choice&gt;Async</c> extension methods for the <c>TransferFactory</c> Daml interface.
/// One method per choice; each submits an interface-typed
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> built via
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand.For{TOwner}(global::Daml.Runtime.Contracts.ContractId{TOwner},global::Daml.Runtime.Commands.ChoiceName,global::Daml.Runtime.Data.DamlValue)"/>
/// through <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
/// and projects the committed transaction's matching exercise event through the choice
/// descriptor's <c>ResultDecoder</c>, surfacing a typed
/// <see cref="global::Daml.Runtime.Outcomes.ExerciseOutcome{TResult}"/> — the choice's own return
/// type, not the implementing template's. A decode failure after a successful commit
/// surfaces as <see cref="global::Daml.Runtime.Outcomes.ExerciseOutcome{TResult}.CommittedUndecodable"/>,
/// never as a resubmittable error.
/// </summary>
public static class ITransferFactoryExtensions
{
    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>Archive</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand ArchiveCommand(
        this global::Daml.Runtime.Contracts.ContractId<ITransferFactory> contractId)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        return global::Daml.Runtime.Commands.ExerciseCommand.For<ITransferFactory>(contractId, new global::Daml.Runtime.Commands.ChoiceName("Archive"), global::Daml.Runtime.Data.DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the <c>Archive</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceArchive.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit>> TryArchiveAsync(
        this global::Daml.Runtime.Contracts.ContractId<ITransferFactory> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>TransferFactory_PublicFetch</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand TransferFactory_PublicFetchCommand(
        this global::Daml.Runtime.Contracts.ContractId<ITransferFactory> contractId,
        global::Splice.Api.Token.TransferInstructionV2.TransferFactory_PublicFetch argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return global::Daml.Runtime.Commands.ExerciseCommand.For<ITransferFactory>(contractId, new global::Daml.Runtime.Commands.ChoiceName("TransferFactory_PublicFetch"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>TransferFactory_PublicFetch</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceTransferFactory_PublicFetch.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView>> TryTransferFactory_PublicFetchAsync(
        this global::Daml.Runtime.Contracts.ContractId<ITransferFactory> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Api.Token.TransferInstructionV2.TransferFactory_PublicFetch argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.TransferFactory_PublicFetchCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectTransferFactory_PublicFetchResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>TransferFactory_Transfer</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static global::Daml.Runtime.Commands.ExerciseCommand TransferFactory_TransferCommand(
        this global::Daml.Runtime.Contracts.ContractId<ITransferFactory> contractId,
        global::Splice.Api.Token.TransferInstructionV2.TransferFactory_Transfer argument)
    {
        global::System.ArgumentNullException.ThrowIfNull(contractId);
        global::System.ArgumentNullException.ThrowIfNull(argument);
        return global::Daml.Runtime.Commands.ExerciseCommand.For<ITransferFactory>(contractId, new global::Daml.Runtime.Commands.ChoiceName("TransferFactory_Transfer"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>TransferFactory_Transfer</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceTransferFactory_Transfer.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="configure">Optional hook that receives the submission built for this call and returns the one to submit, so a caller can add what this helper does not expose: <c>s => s.WithDisclosedContracts(holding.Disclosure!)</c>, <c>WithDeduplicationPeriod</c>, <c>WithSynchronizerId</c> or <c>WithMinLedgerTime</c>. It runs after <c>workflowId</c> and <c>commandId</c> are applied. It must keep the helper's command, and the submitter's act-as and read-as parties replace any set on the submission. The default <c>null</c> submits the submission unchanged.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async global::System.Threading.Tasks.Task<global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.TransferInstructionV2.TransferInstructionResult>> TryTransferFactory_TransferAsync(
        this global::Daml.Runtime.Contracts.ContractId<ITransferFactory> contractId,
        global::Daml.Ledger.Abstractions.ILedgerWriter client,
        global::Splice.Api.Token.TransferInstructionV2.TransferFactory_Transfer argument,
        global::Daml.Runtime.Commands.SubmitterInfo submitter,
        string? workflowId = null,
        global::Daml.Runtime.Commands.CommandId? commandId = null,
        global::System.TimeSpan? timeout = null,
        global::System.Func<global::Daml.Runtime.Commands.CommandsSubmission, global::Daml.Runtime.Commands.CommandsSubmission>? configure = null,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        global::System.ArgumentNullException.ThrowIfNull(client);

        var command = contractId.TransferFactory_TransferCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, configure, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectTransferFactory_TransferResult(tx, contractId.Value));
    }

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Daml.Runtime.Data.DamlUnit> ProjectArchiveResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(ITransferFactory.ChoiceArchive, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.TransferInstructionV2.TransferFactoryView> ProjectTransferFactory_PublicFetchResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(ITransferFactory.ChoiceTransferFactory_PublicFetch, contractId);

    private static global::Daml.Runtime.Outcomes.ExerciseOutcome<global::Splice.Api.Token.TransferInstructionV2.TransferInstructionResult> ProjectTransferFactory_TransferResult(global::Daml.Runtime.Contracts.TransactionResult tx, string contractId) =>
        tx.ProjectChoiceResult(ITransferFactory.ChoiceTransferFactory_Transfer, contractId);
}
