// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.TransferInstructionV2;

/// <summary>
/// Generated from Daml record TransferInstructionAction.TIA_Custom
/// </summary>
public sealed record TransferInstructionAction_TIA_Custom(
    [property: global::Daml.Runtime.Data.DamlFieldAttribute("id")] string Id
) : global::Daml.Runtime.Data.IDamlRecord<TransferInstructionAction_TIA_Custom>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("id", new global::Daml.Runtime.Data.DamlText(Id))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferInstructionAction_TIA_Custom FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new TransferInstructionAction_TIA_Custom(
        Id: record.GetRequiredField("id").As<global::Daml.Runtime.Data.DamlText>().Value
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("id", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "id"), context.Field("id")))
        );
    }

}
