// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.AllocationV2;

/// <summary>
/// Generated from Daml record AllocationSpecification
/// </summary>
public sealed record AllocationSpecification(
    global::Daml.Runtime.Data.Party Admin,
    global::Splice.Api.Token.HoldingV2.Account Authorizer,
    global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.Token.AllocationV2.TransferLegSide> TransferLegSides,
    global::System.DateTimeOffset? SettlementDeadline,
    global::System.Collections.Generic.IReadOnlyDictionary<string, decimal>? NextIterationFunding,
    bool Committed,
    global::Splice.Api.Token.MetadataV1.Metadata Meta
) : global::Daml.Runtime.Data.IDamlRecord<AllocationSpecification>
{
    /// <summary>The Daml field <c>admin</c>.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("admin")]
    public global::Daml.Runtime.Data.Party Admin { get; init; } = Admin;

    /// <summary>The Daml field <c>authorizer</c>.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("authorizer")]
    public global::Splice.Api.Token.HoldingV2.Account Authorizer { get; init; } = Authorizer;

    private readonly global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.Token.AllocationV2.TransferLegSide> _transferLegSides = global::Daml.Runtime.Data.DamlFieldCollections.Copy(TransferLegSides);

    /// <summary>The Daml field <c>transferLegSides</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("transferLegSides")]
    public global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.Token.AllocationV2.TransferLegSide> TransferLegSides
    {
        get => _transferLegSides;
        init => _transferLegSides = global::Daml.Runtime.Data.DamlFieldCollections.Copy(value);
    }

    /// <summary>The Daml field <c>settlementDeadline</c>.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("settlementDeadline")]
    public global::System.DateTimeOffset? SettlementDeadline { get; init; } = SettlementDeadline;

    private readonly global::System.Collections.Generic.IReadOnlyDictionary<string, decimal>? _nextIterationFunding = global::Daml.Runtime.Data.DamlFieldCollections.Copy(NextIterationFunding);

    /// <summary>The Daml field <c>nextIterationFunding</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("nextIterationFunding")]
    public global::System.Collections.Generic.IReadOnlyDictionary<string, decimal>? NextIterationFunding
    {
        get => _nextIterationFunding;
        init => _nextIterationFunding = global::Daml.Runtime.Data.DamlFieldCollections.Copy(value);
    }

    /// <summary>The Daml field <c>committed</c>.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("committed")]
    public bool Committed { get; init; } = Committed;

    /// <summary>The Daml field <c>meta</c>.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("meta")]
    public global::Splice.Api.Token.MetadataV1.Metadata Meta { get; init; } = Meta;

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(AllocationSpecification? other) =>
        other is not null
        && global::System.Collections.Generic.EqualityComparer<global::Daml.Runtime.Data.Party>.Default.Equals(Admin, other.Admin)
        && global::System.Collections.Generic.EqualityComparer<global::Splice.Api.Token.HoldingV2.Account>.Default.Equals(Authorizer, other.Authorizer)
        && global::Daml.Runtime.Data.DamlFieldCollections.Equal(TransferLegSides, other.TransferLegSides)
        && global::System.Collections.Generic.EqualityComparer<global::System.DateTimeOffset?>.Default.Equals(SettlementDeadline, other.SettlementDeadline)
        && global::Daml.Runtime.Data.DamlFieldCollections.Equal(NextIterationFunding, other.NextIterationFunding)
        && global::System.Collections.Generic.EqualityComparer<bool>.Default.Equals(Committed, other.Committed)
        && global::System.Collections.Generic.EqualityComparer<global::Splice.Api.Token.MetadataV1.Metadata>.Default.Equals(Meta, other.Meta);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(Admin);
        hash.Add(Authorizer);
        hash.Add(global::Daml.Runtime.Data.DamlFieldCollections.Hash(TransferLegSides));
        hash.Add(SettlementDeadline);
        hash.Add(global::Daml.Runtime.Data.DamlFieldCollections.Hash(NextIterationFunding));
        hash.Add(Committed);
        hash.Add(Meta);
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("admin", Admin.ToDamlValue()),
        global::Daml.Runtime.Data.DamlField.Create("authorizer", Authorizer.ToRecord()),
        global::Daml.Runtime.Data.DamlField.Create("transferLegSides", new global::Daml.Runtime.Data.DamlList(TransferLegSides.Select(x => (global::Daml.Runtime.Data.DamlValue)x.ToRecord()).ToList())),
        global::Daml.Runtime.Data.DamlField.Create("settlementDeadline", SettlementDeadline is { } __SettlementDeadline ? new global::Daml.Runtime.Data.DamlOptional(new global::Daml.Runtime.Data.DamlTimestamp(__SettlementDeadline)) : global::Daml.Runtime.Data.DamlOptional.None),
        global::Daml.Runtime.Data.DamlField.Create("nextIterationFunding", NextIterationFunding is { } __NextIterationFunding ? new global::Daml.Runtime.Data.DamlOptional(new global::Daml.Runtime.Data.DamlTextMap(__NextIterationFunding.ToDictionary(kv => kv.Key, kv => (global::Daml.Runtime.Data.DamlValue)new global::Daml.Runtime.Data.DamlNumeric(kv.Value)))) : global::Daml.Runtime.Data.DamlOptional.None),
        global::Daml.Runtime.Data.DamlField.Create("committed", new global::Daml.Runtime.Data.DamlBool(Committed)),
        global::Daml.Runtime.Data.DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationSpecification FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new AllocationSpecification(
        Admin: global::Daml.Runtime.Data.Party.FromDamlValue(record.GetRequiredField("admin").As<global::Daml.Runtime.Data.DamlParty>()),
        Authorizer: global::Splice.Api.Token.HoldingV2.Account.FromRecord(record.GetRequiredField("authorizer").As<global::Daml.Runtime.Data.DamlRecord>()),
        TransferLegSides: (global::System.Collections.Generic.IReadOnlyList<global::Splice.Api.Token.AllocationV2.TransferLegSide>)record.GetRequiredField("transferLegSides").As<global::Daml.Runtime.Data.DamlList>().Values.Select(x => global::Splice.Api.Token.AllocationV2.TransferLegSide.FromRecord(x.As<global::Daml.Runtime.Data.DamlRecord>())).ToList(),
        SettlementDeadline: record.GetOptionalField("settlementDeadline").AsOptional().HasValue ? record.GetOptionalField("settlementDeadline").AsOptional().Value!.As<global::Daml.Runtime.Data.DamlTimestamp>().Value : null,
        NextIterationFunding: record.GetOptionalField("nextIterationFunding").AsOptional().HasValue ? (global::System.Collections.Generic.IReadOnlyDictionary<string, decimal>)record.GetOptionalField("nextIterationFunding").AsOptional().Value!.As<global::Daml.Runtime.Data.DamlTextMap>().Values.ToDictionary(kv => kv.Key, kv => kv.Value.As<global::Daml.Runtime.Data.DamlNumeric>().Value) : null,
        Committed: record.GetRequiredField("committed").As<global::Daml.Runtime.Data.DamlBool>().Value,
        Meta: global::Splice.Api.Token.MetadataV1.Metadata.FromRecord(record.GetRequiredField("meta").As<global::Daml.Runtime.Data.DamlRecord>())
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        var fields = new global::System.Collections.Generic.List<global::Daml.Runtime.Data.DamlField>(7);
        fields.Add(global::Daml.Runtime.Data.DamlField.Create("admin", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "admin"), context.Field("admin"))));
        fields.Add(global::Daml.Runtime.Data.DamlField.Create("authorizer", global::Splice.Api.Token.HoldingV2.Account.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "authorizer"), context.Field("authorizer"))));
        fields.Add(global::Daml.Runtime.Data.DamlField.Create("transferLegSides", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "transferLegSides"), context.Field("transferLegSides"), (__json0, __ctx0) => global::Splice.Api.Token.AllocationV2.TransferLegSide.__ReadDamlLfJson(__json0, __ctx0))));
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.AddFieldIfPresent(fields, json, "settlementDeadline", present => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadOptional(present, context.Field("settlementDeadline"), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadTimestamp(__json0, __ctx0)));
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.AddFieldIfPresent(fields, json, "nextIterationFunding", present => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadOptional(present, context.Field("nextIterationFunding"), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadTextMap(__json0, __ctx0, (__json1, __ctx1) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadNumeric(__json1, __ctx1))));
        fields.Add(global::Daml.Runtime.Data.DamlField.Create("committed", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadBool(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "committed"), context.Field("committed"))));
        fields.Add(global::Daml.Runtime.Data.DamlField.Create("meta", global::Splice.Api.Token.MetadataV1.Metadata.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "meta"), context.Field("meta"))));
        return global::Daml.Runtime.Data.DamlRecord.Create(fields.ToArray());
    }

}
