// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.AllocationV2;

/// <summary>
/// Generated from Daml record Allocation_Cancel
/// </summary>
public sealed record Allocation_Cancel(
    global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party> Actors,
    global::Splice.Api.Token.MetadataV1.ExtraArgs ExtraArgs
) : global::Daml.Runtime.Data.IDamlRecord<Allocation_Cancel>
{
    private readonly global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party> _actors = global::Daml.Runtime.Data.DamlFieldCollections.Copy(Actors);

    /// <summary>The Daml field <c>actors</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("actors")]
    public global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party> Actors
    {
        get => _actors;
        init => _actors = global::Daml.Runtime.Data.DamlFieldCollections.Copy(value);
    }

    /// <summary>The Daml field <c>extraArgs</c>.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("extraArgs")]
    public global::Splice.Api.Token.MetadataV1.ExtraArgs ExtraArgs { get; init; } = ExtraArgs;

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(Allocation_Cancel? other) =>
        other is not null
        && global::Daml.Runtime.Data.DamlFieldCollections.Equal(Actors, other.Actors)
        && global::System.Collections.Generic.EqualityComparer<global::Splice.Api.Token.MetadataV1.ExtraArgs>.Default.Equals(ExtraArgs, other.ExtraArgs);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(global::Daml.Runtime.Data.DamlFieldCollections.Hash(Actors));
        hash.Add(ExtraArgs);
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("actors", new global::Daml.Runtime.Data.DamlList(Actors.Select(x => (global::Daml.Runtime.Data.DamlValue)x.ToDamlValue()).ToList())),
        global::Daml.Runtime.Data.DamlField.Create("extraArgs", ExtraArgs.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static Allocation_Cancel FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new Allocation_Cancel(
        Actors: (global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party>)record.GetRequiredField("actors").As<global::Daml.Runtime.Data.DamlList>().Values.Select(x => global::Daml.Runtime.Data.Party.FromDamlValue(x.As<global::Daml.Runtime.Data.DamlParty>())).ToList(),
        ExtraArgs: global::Splice.Api.Token.MetadataV1.ExtraArgs.FromRecord(record.GetRequiredField("extraArgs").As<global::Daml.Runtime.Data.DamlRecord>())
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("actors", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "actors"), context.Field("actors"), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(__json0, __ctx0))),
            global::Daml.Runtime.Data.DamlField.Create("extraArgs", global::Splice.Api.Token.MetadataV1.ExtraArgs.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "extraArgs"), context.Field("extraArgs")))
        );
    }

}
