// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

namespace Splice.Api.Token.AllocationV2;

internal static class PackageRegistration_051a3b0563a6fa4df4cb34448081e48b061e555aa1a265abf6ae8f3f4cafe439
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register()
    {
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Api.Token.AllocationV2.IAllocation>();
        global::Daml.Runtime.Serialization.GeneratedTypeReaders.ForChoices<global::Splice.Api.Token.AllocationV2.ISettlementFactory>();
    }
}
