// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.AllocationV2;

/// <summary>
/// Generated from Daml record SettlementFactory_PublicFetch
/// </summary>
public sealed record SettlementFactory_PublicFetch(
    global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party> Actors
) : global::Daml.Runtime.Data.IDamlRecord<SettlementFactory_PublicFetch>
{
    private readonly global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party> _actors = global::Daml.Runtime.Data.DamlFieldCollections.Copy(Actors);

    /// <summary>The Daml field <c>actors</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [global::Daml.Runtime.Data.DamlFieldAttribute("actors")]
    public global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party> Actors
    {
        get => _actors;
        init => _actors = global::Daml.Runtime.Data.DamlFieldCollections.Copy(value);
    }

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(SettlementFactory_PublicFetch? other) =>
        other is not null
        && global::Daml.Runtime.Data.DamlFieldCollections.Equal(Actors, other.Actors);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(global::Daml.Runtime.Data.DamlFieldCollections.Hash(Actors));
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public global::Daml.Runtime.Data.DamlRecord ToRecord() => global::Daml.Runtime.Data.DamlRecord.Create(
        global::Daml.Runtime.Data.DamlField.Create("actors", new global::Daml.Runtime.Data.DamlList(Actors.Select(x => (global::Daml.Runtime.Data.DamlValue)x.ToDamlValue()).ToList()))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static SettlementFactory_PublicFetch FromRecord(global::Daml.Runtime.Data.DamlRecord record) => new SettlementFactory_PublicFetch(
        Actors: (global::System.Collections.Generic.IReadOnlyList<global::Daml.Runtime.Data.Party>)record.GetRequiredField("actors").As<global::Daml.Runtime.Data.DamlList>().Values.Select(x => global::Daml.Runtime.Data.Party.FromDamlValue(x.As<global::Daml.Runtime.Data.DamlParty>())).ToList()
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return global::Daml.Runtime.Data.DamlRecord.Create(
            global::Daml.Runtime.Data.DamlField.Create("actors", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "actors"), context.Field("actors"), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(__json0, __ctx0)))
        );
    }

}
