// <auto-generated>
// This code was generated by canton-dotnet-sdk.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;

namespace Splice.Api.Token.AllocationV2;

/// <summary>
/// Generated from Daml enum TransferSide
/// </summary>
public enum TransferSide
{
    /// <summary>SenderSide enum constructor.</summary>
    SenderSide,
    /// <summary>ReceiverSide enum constructor.</summary>
    ReceiverSide,
}

/// <summary>
/// Extension methods for TransferSide serialization.
/// </summary>
public static class TransferSideExtensions
{
    /// <summary>Converts to a DamlEnum value.</summary>
    public static global::Daml.Runtime.Data.DamlEnum ToDamlEnum(this global::Splice.Api.Token.AllocationV2.TransferSide value)
    {
        return value switch
        {
            global::Splice.Api.Token.AllocationV2.TransferSide.SenderSide => global::Daml.Runtime.Data.DamlEnum.Create("SenderSide"),
            global::Splice.Api.Token.AllocationV2.TransferSide.ReceiverSide => global::Daml.Runtime.Data.DamlEnum.Create("ReceiverSide"),
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(value), value, null)
        };
    }

    /// <summary>Creates an instance from a DamlEnum value.</summary>
    public static global::Splice.Api.Token.AllocationV2.TransferSide FromDamlEnum(global::Daml.Runtime.Data.DamlEnum value)
    {
        return value.Constructor switch
        {
            "SenderSide" => global::Splice.Api.Token.AllocationV2.TransferSide.SenderSide,
            "ReceiverSide" => global::Splice.Api.Token.AllocationV2.TransferSide.ReceiverSide,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(value), value.Constructor, null)
        };
    }

    /// <summary>Decodes a Daml-LF JSON enum constructor directly into a DamlEnum, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static global::Daml.Runtime.Data.DamlEnum __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context) =>
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadEnumConstructor(json, context, ExpectedConstructors);

    private static readonly string[] ExpectedConstructors = ["SenderSide", "ReceiverSide"];

}
