// Copyright 2026 Peaceful Studio OÜ
// SPDX-License-Identifier: Apache-2.0

using System.Linq.Expressions;
using Daml.Runtime.Contracts;

namespace Canton.Ledger.Abstractions;

/// <summary>
/// Builds type-safe PQS query filters using expressions.
/// Field names are resolved from strongly-typed expressions against the generated Daml C# bindings,
/// ensuring they always match the PQS JSON payload structure.
/// </summary>
/// <example>
/// <code>
/// // Single field equality
/// Filter.Field&lt;Agreement&gt;(a => a.Initiator, partyId)
///
/// // OR condition
/// Filter.Or(
///     Filter.Field&lt;Agreement&gt;(a => a.Initiator, partyId),
///     Filter.Field&lt;Agreement&gt;(a => a.Counterparty, partyId))
///
/// // AND condition
/// Filter.And(
///     Filter.Field&lt;Agreement&gt;(a => a.Status, "Active"),
///     Filter.Field&lt;Agreement&gt;(a => a.Initiator, partyId))
/// </code>
/// </example>
public static class Filter
{
    /// <summary>
    /// Creates a filter that matches contracts where the specified field equals the given value.
    /// The field name is resolved from the codegen-emitted <c>[DamlField]</c> metadata on the
    /// selected property, so it matches the PQS JSON payload key exactly. The value is parsed as the
    /// field's Daml type with the invariant culture and compared as that type, so <c>"42.5"</c>
    /// matches a <c>Numeric</c> field stored as <c>42.5000000000</c>. A <c>Numeric</c> value keeps every
    /// digit it is given, beyond the precision of <see cref="decimal"/>. A selected <c>Optional</c> field
    /// compares its carried value.
    /// </summary>
    /// <typeparam name="T">The Daml template type.</typeparam>
    /// <param name="selector">
    /// A selector reaching a leaf field, possibly through nested records (e.g., <c>a => a.Terms.Initiator</c>).
    /// </param>
    /// <param name="value">The value to match, in the Daml wire text form of the field's type.</param>
    /// <returns>A filter matching contracts where the specified field equals the given value.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="selector"/> does not reach a Daml leaf field through property access, or
    /// <paramref name="value"/> is not a valid value of the field's Daml type.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// The selected property carries no <c>[DamlField]</c> metadata (bindings generated by a
    /// pre-metadata codegen); regenerate the Daml bindings before using the typed filter DSL.
    /// </exception>
    public static PqsFilter Field<T>(Expression<Func<T, object?>> selector, string value)
        where T : ITemplate
    {
        ArgumentNullException.ThrowIfNull(selector);
        ArgumentNullException.ThrowIfNull(value);
        return PqsPredicateTranslator.FieldEquals(selector, value);
    }

    /// <summary>
    /// Creates a filter from a C# predicate over the template's generated Daml bindings, translated
    /// into a parameterized SQL predicate over the PQS JSON payload. Every comparison is typed by the
    /// selected field's Daml type, so a <c>Numeric</c> compares as a number, a <c>Time</c> as a
    /// timestamp, and so on.
    /// </summary>
    /// <remarks>
    /// <para>The predicate may use:</para>
    /// <list type="bullet">
    /// <item><description>
    /// <c>==</c> and <c>!=</c> on any leaf field (<c>Text</c>, <c>Int64</c>, <c>Numeric</c>, <c>Bool</c>,
    /// <c>Date</c>, <c>Time</c>, <c>Party</c>, <c>ContractId</c>, enum), and <c>&lt;</c>, <c>&lt;=</c>,
    /// <c>&gt;</c>, <c>&gt;=</c> on <c>Int64</c>, <c>Numeric</c>, <c>Date</c> and <c>Time</c>, against a
    /// captured value. A bare <c>Bool</c> field reads as <c>== true</c>.
    /// </description></item>
    /// <item><description>Nested record fields and tuple components (<c>_1</c>, <c>_2</c>, <c>_3</c>).</description></item>
    /// <item><description>
    /// <c>Optional</c>: <c>== null</c> / <c>!= null</c> on a nullable field, <c>.HasValue</c>,
    /// <c>is Optional&lt;T&gt;.Some</c> / <c>is Optional&lt;T&gt;.None</c>, and reading the value through
    /// <c>.Value</c>, <c>.GetValueOrDefault()</c> or a cast to <c>Optional&lt;T&gt;.Some</c>. A <c>None</c>
    /// never equals a value and always differs from one, except under <c>.GetValueOrDefault()</c> on a
    /// value type: there a <c>None</c> reads as the C# default (<c>0</c> for <c>Int64</c> and
    /// <c>Numeric</c>, <c>false</c> for <c>Bool</c>, the first constructor of an enum, the minimum
    /// <c>Date</c> and <c>Time</c>), and <c>.GetValueOrDefault()</c> on a <c>Party</c> is rejected.
    /// </description></item>
    /// <item><description>
    /// Variants, <c>Either</c> included: <c>is</c> a constructor type, and a cast (or <c>as</c>) to a
    /// constructor type to read its <c>Value</c>, which only matches contracts holding that constructor, while <c>(x as Constructor) == null</c> matches every contract holding a different constructor.
    /// </description></item>
    /// <item><description>
    /// <c>List</c>: <c>Contains(value)</c>, <c>Any()</c>, <c>Any(element => ...)</c> and
    /// <c>All(element => ...)</c>, where the element predicate uses the same forms.
    /// </description></item>
    /// <item><description>
    /// <c>Map</c> and <c>TextMap</c>: <c>map[key]</c> and <c>ContainsKey(key)</c> with a captured key.
    /// A missing key reads as absent: <c>==</c> and ordering do not match it, and <c>!=</c> does.
    /// </description></item>
    /// <item><description><c>&amp;&amp;</c>, <c>||</c> and <c>!</c>.</description></item>
    /// </list>
    /// </remarks>
    /// <example>
    /// <code>
    /// Filter.Where&lt;Invoice&gt;(i => i.Amount &gt; 100m &amp;&amp; i.Status == InvoiceStatus.Open)
    /// </code>
    /// </example>
    /// <typeparam name="T">The Daml template type.</typeparam>
    /// <param name="predicate">The predicate matching contracts must satisfy.</param>
    /// <returns>A filter matching contracts that satisfy <paramref name="predicate"/>.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="predicate"/> uses a construct the PQS translation does not support.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// A selected property carries no <c>[DamlField]</c> metadata; regenerate the Daml bindings.
    /// </exception>
    public static PqsFilter Where<T>(Expression<Func<T, bool>> predicate)
        where T : ITemplate
    {
        ArgumentNullException.ThrowIfNull(predicate);
        return PqsPredicateTranslator.Where(predicate);
    }

    /// <summary>
    /// Combines filters with OR logic.
    /// </summary>
    public static PqsFilter Or(params PqsFilter[] filters)
    {
        ArgumentNullException.ThrowIfNull(filters);
        if (filters.Length == 0)
            throw new ArgumentException("At least one filter is required.", nameof(filters));
        for (var i = 0; i < filters.Length; i++)
            ArgumentNullException.ThrowIfNull(filters[i], $"filters[{i}]");
        return filters.Length == 1 ? filters[0] : new PqsAny([.. filters]);
    }

    /// <summary>
    /// Combines filters with AND logic.
    /// </summary>
    public static PqsFilter And(params PqsFilter[] filters)
    {
        ArgumentNullException.ThrowIfNull(filters);
        if (filters.Length == 0)
            throw new ArgumentException("At least one filter is required.", nameof(filters));
        for (var i = 0; i < filters.Length; i++)
            ArgumentNullException.ThrowIfNull(filters[i], $"filters[{i}]");
        return filters.Length == 1 ? filters[0] : new PqsAll([.. filters]);
    }
}
